### PR TITLE
vote17, Variant 2: Ball holding

### PR DESCRIPTION
**Pull request by babaev1**
Ball holding
During the virtual competition, it became apparent that the current ball-holding rules are too strict, especially when it comes to ball holding between multiple robots. At the moment, the rules state:
holds the ball for more than 1 second in a way that the ball cannot be removed from
the player. […] More than half of the ball’s volume must be outside the convex hull of the player, projected to the ground, for the ball to be considered removable. If the ball enters the convex hull repeatedly, it must be removable in between for the majority of 940 the time. If more than one player of a team is in the vicinity of the ball (defined as less than 0.75m in KidSize and 1.5m in AdultSize), the convex hull is taken around all the players of a team, which prevent the removal of the ball.
We have seen that applying the rule strictly as the autoreferee does lead to a lot of free kicks. We see two options for improving this rule:

2.	For ball holding between multiple robots, we could decrease the definition of the vicinity of the ball. The aim of the rule is to prevent robots from forming a circle around the ball that would make it impossible for robots of the opposing team to approach the ball without committing a forceful contact offense. However, at the moment the circle means that two robots could potentially be 1.5 m away from each other in KidSize and still commit ball holding, even though it would clearly be possible for other players to take the ball. So decreasing the definition of the vicinity of the ball could prevent penalizing robots too often for ball holding.
vicinity definition is reduced to 0.5 m for Kid size and 1.0 m for Adult Size

### CODE REVIEW

**Comment by jgueldenstein** [comment]
As in the discussion, this should be reduced to half of the previous value, so 0.375 for kid and 0.75 in adult as proposed here https://hl.forum.robocup.org/t/discussion-ball-holding/540

**Comment by babaev1** [comment]
vicinity definition is reduced to 0.375 m for Kid size and 0.75 m for Adult Size

**Comment by babaev1** [comment]
Resolved

  
>Четверг, 3 февраля 2022, 17:50 +03:00 от Jasper ***@***.***>:
> 
> 
>As in the discussion, this should be reduced to half of the previous value, so 0.375 for kid and 0.75 in adult as proposed here  https://hl.forum.robocup.org/t/discussion-ball-holding/540
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <RoboCup-Humanoid-TC/Rules/pull/29/c1029067042 @ github . com> 
 
 
--
A B
Отправлено из Почты  Mail.ru

**Comment by MaikePaetzel** [comment]
According to the votes on G01Q17, this received a majority of the votes and this PR will hence be merged into the Master

**Pull request merged**
